#ifndef _ILI9341_t3_font_CormorantGaramond-LightItalic_
#define _ILI9341_t3_font_CormorantGaramond-LightItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t CormorantGaramondLight_8_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_9_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_10_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_11_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_12_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_13_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_14_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_16_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_18_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_20_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_24_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_28_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_32_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_40_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_48_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_60_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_72_Italic;
extern const ILI9341_t3_font_t CormorantGaramondLight_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
