#ifndef _ILI9341_t3_font_CormorantGaramond-SemiBoldItalic_
#define _ILI9341_t3_font_CormorantGaramond-SemiBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t CormorantGaramondSemiBold_8_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_9_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_10_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_11_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_12_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_13_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_14_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_16_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_18_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_20_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_24_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_28_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_32_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_40_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_48_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_60_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_72_Italic;
extern const ILI9341_t3_font_t CormorantGaramondSemiBold_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
