#ifndef _ILI9341_t3_font_FiraSansExtraCondensed-ThinItalic_
#define _ILI9341_t3_font_FiraSansExtraCondensed-ThinItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_8_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_9_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_10_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_11_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_12_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_13_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_14_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_16_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_18_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_20_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_24_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_28_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_32_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_40_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_48_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_60_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_72_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedThin_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
