#ifndef _ILI9341_t3_font_FiraSansExtraCondensed-MediumItalic_
#define _ILI9341_t3_font_FiraSansExtraCondensed-MediumItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_8_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_9_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_10_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_11_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_12_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_13_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_14_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_16_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_18_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_20_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_24_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_28_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_32_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_40_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_48_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_60_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_72_Italic;
extern const ILI9341_t3_font_t FiraSansExtraCondensedMedium_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
