#ifndef _ILI9341_t3_font_MerriweatherSans-ExtraBoldItalic_
#define _ILI9341_t3_font_MerriweatherSans-ExtraBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t MerriweatherSansExtraBold_8_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_9_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_10_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_11_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_12_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_13_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_14_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_16_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_18_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_20_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_24_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_28_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_32_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_40_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_48_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_60_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_72_Italic;
extern const ILI9341_t3_font_t MerriweatherSansExtraBold_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
