#ifndef _ILI9341_t3_font_SourceSansPro-ExtraLightItalic_
#define _ILI9341_t3_font_SourceSansPro-ExtraLightItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t SourceSansProExtraLight_8_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_9_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_10_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_11_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_12_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_13_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_14_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_16_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_18_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_20_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_24_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_28_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_32_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_40_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_48_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_60_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_72_Italic;
extern const ILI9341_t3_font_t SourceSansProExtraLight_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
