#ifndef _ILI9341_t3_font_OpenSansHebrewCondensed-LightItalic_
#define _ILI9341_t3_font_OpenSansHebrewCondensed-LightItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_8_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_9_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_10_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_11_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_12_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_13_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_14_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_16_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_18_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_20_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_24_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_28_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_32_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_40_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_48_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_60_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_72_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensedLight_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
