#ifndef _ILI9341_t3_font_OpenSansHebrewCondensed-BoldItalic_
#define _ILI9341_t3_font_OpenSansHebrewCondensed-BoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t OpenSansHebrewCondensed_8_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_9_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_10_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_11_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_12_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_13_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_14_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_16_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_18_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_20_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_24_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_28_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_32_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_40_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_48_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_60_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_72_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewCondensed_96_Bold_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
