#ifndef _ILI9341_t3_font_SairaExtraCondensed-ExtraLight_
#define _ILI9341_t3_font_SairaExtraCondensed-ExtraLight_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_8;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_9;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_10;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_11;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_12;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_13;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_14;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_16;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_18;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_20;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_24;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_28;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_32;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_40;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_48;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_60;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_72;
extern const ILI9341_t3_font_t SairaExtraCondensedExtraLight_96;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
