#ifndef _ILI9341_t3_font_OpenSansHebrew-ExtraBoldItalic_
#define _ILI9341_t3_font_OpenSansHebrew-ExtraBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_8_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_9_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_10_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_11_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_12_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_13_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_14_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_16_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_18_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_20_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_24_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_28_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_32_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_40_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_48_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_60_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_72_Bold_Italic;
extern const ILI9341_t3_font_t OpenSansHebrewExtraBold_96_Bold_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
