#ifndef _ILI9341_t3_font_FiraSansCondensed-SemiBoldItalic_
#define _ILI9341_t3_font_FiraSansCondensed-SemiBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_8_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_9_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_10_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_11_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_12_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_13_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_14_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_16_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_18_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_20_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_24_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_28_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_32_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_40_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_48_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_60_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_72_Italic;
extern const ILI9341_t3_font_t FiraSansCondensedSemiBold_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
