#ifndef _ILI9341_t3_font_CormorantInfant-SemiBoldItalic_
#define _ILI9341_t3_font_CormorantInfant-SemiBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t CormorantInfantSemiBold_8_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_9_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_10_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_11_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_12_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_13_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_14_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_16_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_18_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_20_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_24_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_28_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_32_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_40_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_48_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_60_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_72_Italic;
extern const ILI9341_t3_font_t CormorantInfantSemiBold_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
