#ifndef _ILI9341_t3_font_PlayfairDisplaySC-BoldItalic_
#define _ILI9341_t3_font_PlayfairDisplaySC-BoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t PlayfairDisplaySC_8_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_9_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_10_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_11_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_12_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_13_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_14_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_16_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_18_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_20_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_24_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_28_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_32_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_40_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_48_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_60_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_72_Bold_Italic;
extern const ILI9341_t3_font_t PlayfairDisplaySC_96_Bold_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
