#ifndef _ILI9341_t3_font_BarlowSemiCondensed-SemiBoldItalic_
#define _ILI9341_t3_font_BarlowSemiCondensed-SemiBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_8_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_9_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_10_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_11_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_12_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_13_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_14_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_16_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_18_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_20_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_24_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_28_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_32_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_40_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_48_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_60_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_72_Italic;
extern const ILI9341_t3_font_t BarlowSemiCondensedSemiBold_96_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
